# CircleCI build config to test different versions of Singuarity
version: 2.1

orbs:
  singularity: singularity/singularity@1.0.3

workflows:
  version: 2
  test:
    jobs:
      - test-singularity-3-python-3:
          filters:
            branches:
              ignore: master
      - test-singularity-3-python-2:
          filters:
            branches:
              ignore: master
      - test-singularity-2-python-2:
          filters:
            branches:
              ignore: master
      - test-singularity-2-python-3:
          filters:
            branches:
              ignore: master

waitforapt: &waitforapt
  name: Remove cloud init lock
  command: |
      while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 10; done
      while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do echo 'Waiting for autoupdates to complete...'; sleep 10; done
      echo 'Waiting for instance to really be ready...'
      sleep 30
      sudo rm -rf /var/lib/apt/lists/lock
      sudo rm /var/lib/dpkg/lock && sudo dpkg --configure -a


install_spython: &install_spython
  name: install spython
  command: |
     $HOME/conda/bin/pip uninstall spython --yes || echo "Not installed"
     $HOME/conda/bin/python setup.py install

install_python_3: &install_python_3
  name: install Python 3.5 dependencies
  command: | 
      ls $HOME
      if [ ! -d "/home/circleci/conda" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
          export PATH=$HOME/conda/bin:$PATH
          $HOME/conda/bin/python setup.py install
       else
           echo "Miniconda 3 is already installed, continuing to build."
       fi

install_python_2: &install_python_2
  name: install Python 3.5 dependencies
  command: | 
      ls $HOME
      if [ ! -d "/home/circleci/conda" ]; then
          wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
          /bin/bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/conda
          export PATH=$HOME/conda/bin:$PATH
          $HOME/conda/bin/python setup.py install
       else
           echo "Miniconda 2 is already installed, continuing to build."
       fi

run_linter: &run_linter
  name: run linter
  command: |
     $HOME/conda/bin/pip install --upgrade pylint
     cd ~/repo
     $HOME/conda/bin/pylint spython

test_spython: &test_spython
  name: Test Singularity Python (Singularity Version 2 and 3)
  command: |
        cd ~/repo/spython
        $HOME/conda/bin/python -m unittest tests.test_recipe
        $HOME/conda/bin/python -m unittest tests.test_parsers
        $HOME/conda/bin/python -m unittest tests.test_writers
        $HOME/conda/bin/python -m unittest tests.test_client
        $HOME/conda/bin/python -m unittest tests.test_utils
        $HOME/conda/bin/python -m unittest tests.test_instances

test_spython_3: &test_spython_3
  name: Test Singularity Python (Singularity Version 3 Only)
  command: |
        cd ~/repo/spython
        $HOME/conda/bin/python -m unittest tests.test_oci


jobs:
  test-singularity-3-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: *install_python_3
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.2.1
      - run: *install_spython
      - run: *run_linter
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v1-dependencies        
      - run: *test_spython
      - run: *test_spython_3

  test-singularity-3-python-2:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: *install_python_2
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.2.1
      - run: *install_spython
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v1-dependencies        
      - run: *test_spython
      - run: *test_spython_3

  test-singularity-2-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: *install_python_3
      - run: *waitforapt
      - singularity/debian-install-2:
          singularity-version: 2.6.1
      - run: *install_spython
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v1-dependencies        
      - run: *test_spython

  test-singularity-2-python-2:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: *install_python_2
      - run: *waitforapt
      - singularity/debian-install-2:
          singularity-version: 2.6.1
      - run: *install_spython
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v1-dependencies        
      - run: *test_spython
