# CircleCI build config to test different versions of Singuarity
version: 2.1

orbs:
  singularity: singularity/singularity@1.0.4

workflows:
  version: 2
  test:
    jobs:
      - test-singularity-3-python-3: &ignore_master
          filters:
            branches:
              ignore: master
      - test-singularity-3-1-python-3: *ignore_master
      - test-singularity-3-2-python-3: *ignore_master
      - test-singularity-3-python-2: *ignore_master
      - test-singularity-2-python-3: *ignore_master
      - test-singularity-2-python-2: *ignore_master

waitforapt: &waitforapt
  name: Remove cloud init lock
  command: |
      while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 10; done
      while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do echo 'Waiting for autoupdates to complete...'; sleep 10; done
      echo 'Waiting for instance to really be ready...'
      sleep 30
      sudo rm -rf /var/lib/apt/lists/lock
      sudo rm /var/lib/dpkg/lock && sudo dpkg --configure -a


install_spython: &install_spython
  name: install spython
  command: |
      pip uninstall spython --yes || echo "Not installed"
      python --version
      python setup.py install

install_python_3: &install_python_3
  name: install Python 3 dependencies
  command: | 
      echo 'export PATH="$HOME/conda/bin:$PATH"' >> "$BASH_ENV"
      source "$BASH_ENV"
      if [ ! -d "$HOME/conda" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
      else
           echo "Miniconda 3 is already installed, continuing to build."
      fi
      [ $(python -c'import sys;print(sys.version_info.major)') -eq 3 ]

install_python_2: &install_python_2
  name: install Python 2 dependencies
  command: | 
      echo 'export PATH="$HOME/conda/bin:$PATH"' >> "$BASH_ENV"
      if [ ! -d "$HOME/conda" ]; then
          wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
          /bin/bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/conda
      else
           echo "Miniconda 2 is already installed, continuing to build."
      fi
      [ $(python -c'import sys;print(sys.version_info.major)') -eq 2 ]

install_dependencies: &install_dependencies
  name: install CI dependencies
  command: |
      pip install --upgrade pylint pytest

run_linter: &run_linter
  name: run linter
  command: |
      cd ~/repo
      pylint spython

test_spython: &test_spython
  name: Test Singularity Python
  command: pytest ~/repo/spython

jobs:
  test-singularity-3-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py3
      - run: *install_python_3
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.2.1
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py3
      - run: *run_linter
      - run: *test_spython

  test-singularity-3-1-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py3
      - run: *install_python_3
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.1.0
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py3
      - run: *test_spython

  test-singularity-3-2-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py3
      - run: *install_python_3
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.2.0
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py3
      - run: *test_spython

  test-singularity-3-python-2:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py2
      - run: *install_python_2
      - run: *waitforapt
      - singularity/install-go:
          go-version: 1.11.5
      - singularity/debian-install-3:
          singularity-version: 3.2.1
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py2
      - run: *test_spython

  test-singularity-2-python-3:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py3
      - run: *install_python_3
      - run: *waitforapt
      - singularity/debian-install-2:
          singularity-version: 2.6.1
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py3
      - run: *test_spython

  test-singularity-2-python-2:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-py2
      - run: *install_python_2
      - run: *waitforapt
      - singularity/debian-install-2:
          singularity-version: 2.6.1
      - run: *install_spython
      - run: *install_dependencies
      - save_cache:
          paths:
            - ~/conda
          key: v1-dependencies-py2
      - run: *test_spython
